call git submodule add https://github.com/kohana/cache.git modules/cache
call git submodule add https://github.com/kohana/codebench.git modules/codebench
call git submodule add https://github.com/kohana/database.git modules/database
call git submodule add https://github.com/kohana/image.git modules/image
call git submodule add https://github.com/kohana/minion.git modules/minion
call git submodule add https://github.com/kohana/orm.git modules/orm
call git submodule add https://github.com/kohana/unittest.git modules/unittest
call git submodule add https://github.com/kohana/userguide.git modules/userguide
call git submodule add https://github.com/kohana/core.git system
call git submodule add https://github.com/paptamas/kohana-auth.git modules/auth
call git submodule add https://github.com/paptamas/kohana-oauth.git modules/oauth
call git submodule add https://github.com/paptamas/kohana-helpers.git modules/helpers
call git submodule add https://github.com/paptamas/kohana-javascript.git modules/javascript
call git submodule add https://github.com/paptamas/kohana-debugger.git modules/debugger
call git submodule add https://github.com/paptamas/kohana-email.git modules/email